# docker-compose.yml

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=noahCordova
      - POSTGRES_PASSWORD=myPassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres:
